export default [
  {
    id: 0,
    name: 'Hoddie',
    //image: require('./picture2.png'),
    image: 'https://media.istockphoto.com/photos/white-male-hoodie-sweatshirt-long-sleeve-with-clipping-path-mens-picture-id1124815039',
    quantity: 5,
    price: 100,
    add_to_cart: true,
    product_size: ['S', 'M', 'L', 'XL'],
    product_color: ['black', 'red', 'white'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count:1,
  },
  {
    id: 1,
    name: 'Jacket',
    image:
      'https://media.istockphoto.com/photos/young-athlete-starting-her-workout-at-night-picture-id621496952',
    quantity: 10,
    price: 50,
    add_to_cart: true,
    product_size: ['M', 'L', 'XL'],
    product_color: ['blue', 'green', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 2,
    name: 'Hoddie',
    image:
      'https://media.istockphoto.com/photos/girl-with-pink-hair-in-stylish-oversized-casual-hoodie-standing-and-picture-id1300209453?s=612x612',
    quantity: 5,
    price: 210,
    add_to_cart: true,
    product_size: ['S', 'M', 'L', 'XL'],
    product_color: ['red', 'yellow', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 3,
    name: 'T-shirt',
    image:
      'https://media.istockphoto.com/photos/theres-no-one-else-like-you-picture-id1297600922',
    quantity: 3,
    price: 150,
    add_to_cart: true,
    product_size: ['S', 'M', 'L', 'XL'],
    product_color: ['red', 'yellow', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 4,
    name: 'jacket',
    image:
      'https://media.istockphoto.com/photos/little-girl-getting-ready-for-school-picture-id931055460?s=612x612',
    quantity: 3,
    price: 300,
    add_to_cart: true,
    product_size: ['S', 'M', 'L', 'XL'],
    product_color: ['red', 'yellow', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 5,
    name: 'T-shirt',
    image:
      'https://media.istockphoto.com/photos/stylish-blonde-girl-wearing-black-tshirt-and-glasses-posing-against-picture-id1286538907',
    quantity: 3,
    price: 150,
    add_to_cart: true,
    product_size: ['S', 'M', 'L', 'XL'],
    product_color: ['red', 'yellow', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 6,
    name: 'shose',
    image:
      "https://media.istockphoto.com/photos/fashionable-feet-picture-id660449036",
    quantity: 3,
    price: 600,
    add_to_cart: true,
    product_size: ['S', 'M', 'L', 'XL'],
    product_color: ['red', 'yellow', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 7,
    name: 'socks',
    image:
      'https://media.istockphoto.com/photos/female-legs-in-colorful-socks-on-colored-background-picture-id1197321646?s=612x612',
    quantity: 3,
    price: 20,
    add_to_cart: true,
    product_size: ['S', 'M', 'L', 'XL'],
    product_color: ['yellow', 'black', 'blue','pink'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 8,
    name: 'Pants',
    image:
      'https://media.istockphoto.com/photos/stylish-woman-in-pink-wide-legs-trousers-sneakers-and-striped-blouse-picture-id1194439772?s=612x612',
    quantity: 3,
    price: 150,
    add_to_cart: true,
    product_size: ['S', 'M', 'L', 'XL'],
    product_color: ['red', 'yellow', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 9,
    name: 'Pants',
    image:
      'https://media.istockphoto.com/photos/elegant-woman-wearing-high-heels-picture-id873238240?s=612x612',
    quantity: 3,
    price: 250,
    add_to_cart: true,
    product_size: ['S', 'M', 'L', 'XL'],
    product_color: ['red', 'yellow', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 10,
    name: 'shose',
    image:
      'https://media.istockphoto.com/photos/cropped-closeup-image-view-photo-of-nice-attractive-feminine-fit-thin-picture-id1129341836?s=612x612',
    quantity: 10,
    price: 400,
    add_to_cart: true,
    product_size: ['M', 'L', 'XL'],
    product_color: ['blue', 'green', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 11,
    name: 'shose',
    image:
      'https://media.istockphoto.com/photos/pastel-blue-sneakers-on-crossed-legs-casual-footwear-picture-id1180837581?s=612x612',
    quantity: 10,
    price: 320,
    add_to_cart: true,
    product_size: ['M', 'L', 'XL'],
    product_color: ['blue', 'green', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 12,
    name: 'socks',
    image:
      'https://media.istockphoto.com/photos/funny-woman-legs-picture-id1190475627?s=612x612',
    quantity: 10,
    price: 15,
    add_to_cart: true,
    product_size: ['M', 'L', 'XL'],
    product_color: ['blue', 'green', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 12,
    name: 'T-shirt',
    image:
      'https://media.istockphoto.com/photos/portrait-of-a-mixed-race-young-woman-outdoor-picture-id1159432203?s=612x612',
    quantity: 10,
    price: 210,
    add_to_cart: true,
    product_size: ['M', 'L', 'XL'],
    product_color: ['blue', 'green', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 12,
    name: 'T-shirt',
    image:
      'https://media.istockphoto.com/photos/portrait-of-tattooed-young-man-picture-id1148212557?s=612x612',
    quantity: 10,
    price: 400,
    add_to_cart: true,
    product_size: ['S','M', 'L', 'XL'],
    product_color: ['blue', 'green', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 13,
    name: 'jacket',
    image:
      'https://media.istockphoto.com/photos/male-coat-isolated-on-the-white-picture-id163208487',
    quantity: 10,
    price: 300,
    add_to_cart: true,
    product_size: ['S','M', 'L', 'XL'],
    product_color: ['blue', 'black', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 14,
    name: 'jacket',
    image:
      'https://media.istockphoto.com/photos/outdoor-portrait-of-man-leaning-against-wooden-building-picture-id544445328?s=612x612',
    quantity: 10,
    price: 400,
    add_to_cart: true,
    product_size: ['S','M', 'L', 'XL'],
    product_color: ['blue', 'black', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 15,
    name: 'hoddie',
    image:
      'https://media.istockphoto.com/photos/smiling-hipster-gen-z-teen-girl-with-pink-hair-wear-hoodie-sit-on-bed-picture-id1266949848',
    quantity: 10,
    price: 190,
    add_to_cart: true,
    product_size: ['S','M', 'L', 'XL'],
    product_color: ['blue', 'black', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 16,
    name: 'hoddie',
    image:
      'https://media.istockphoto.com/photos/portrait-of-a-serious-teen-looking-at-camera-picture-id887424442',
    quantity: 10,
    price: 180,
    add_to_cart: true,
    product_size: ['S','M', 'L', 'XL'],
    product_color: ['blue', 'black', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 17,
    name: 'pants',
    image:
      'https://media.istockphoto.com/photos/skinny-tight-blue-jeans-on-white-background-picture-id171269123',
    quantity: 10,
    price: 270,
    add_to_cart: true,
    product_size: ['S','M', 'L', 'XL'],
    product_color: ['blue', 'black', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 18,
    name: 'pants',
    image:
      'https://media.istockphoto.com/photos/legs-athlete-runner-picture-id1166985803',
    quantity: 10,
    price: 250,
    add_to_cart: true,
    product_size: ['S','M', 'L', 'XL'],
    product_color: ['blue', 'black', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 19,
    name: 'shose',
    image:
      'https://media.istockphoto.com/photos/canvas-shoes-picture-id171224469?s=612x612',
    quantity: 10,
    price: 160,
    add_to_cart: true,
    product_size: ['S','M', 'L', 'XL'],
    product_color: ['blue', 'black', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 20,
    name: 'socks',
    image:
      'https://media.istockphoto.com/photos/funny-cotton-mens-socks-picture-id1179628157?s=612x612',
    quantity: 10,
    price: 15,
    add_to_cart: true,
    product_size: ['S','M', 'L', 'XL'],
    product_color: ['blue', 'black', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
  {
    id: 21,
    name: 'socks',
    image:
      'https://media.istockphoto.com/photos/red-white-striped-socks-picture-id1149383049?s=612x612',
    quantity: 10,
    price: 13,
    add_to_cart: true,
    product_size: ['S','M', 'L', 'XL'],
    product_color: ['blue', 'black', 'grey'],
    select_size: '',
    select_color: '',
    heart_active: true,
    product_count: 1,
  },
];